language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
matrix:
  include:
    - elixir: 1.6
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.9
      otp_release: 22.0
    - elixir: 1.6
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.9
      otp_release: 22.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
script:
  - mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
